version: '2'

services:
  web:
    env_file: .env
    image: datacite/lagottino
    build: .
    ports:
      - "8085:80"
    volumes:
      - ./app:/home/app/webapp/app
      - ./config:/home/app/webapp/config
      - ./db:/home/app/webapp/db
      - ./lib:/home/app/webapp/lib
      - ./spec:/home/app/webapp/spec
    networks:
      - public
  memcached:
    image: memcached:1.4.31
    networks:
      - public
  mysql:
    environment:
      MYSQL_DATABASE: lagotto
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    image: mysql:5.7
    ports:
      - "3313:3306"
    networks:
      - public
networks:
  public:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.80.0/24
        gateway: 10.0.80.1
