version: '2.1'

services:
  web:
    env_file: .env
    environment:
      - ELASTIC_PASSWORD=changeme
    image: datacite/lagottino
    build: .
    ports:
      - "8085:80"
    volumes:
      - ./app:/home/app/webapp/app
      - ./config:/home/app/webapp/config
      - ./db:/home/app/webapp/db
      - ./lib:/home/app/webapp/lib
      - ./spec:/home/app/webapp/spec
      - ./storage:/home/app/webapp/storage
    networks:
      - public
    depends_on:
      elasticsearch:
        condition: service_healthy
  memcached:
    image: memcached:1.4.31
    networks:
      - public
  mysql:
    environment:
      MYSQL_DATABASE: lagotto
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    image: mysql:5.7
    ports:
      - "3313:3306"
    networks:
      - public
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.7
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      ELASTIC_PASSWORD: changeme
    networks:
      - public
    healthcheck:
      test: curl -f http://elastic:changeme@elasticsearch:9200
      interval: 10s
      timeout: 1s
networks:
  public:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.80.0/24
        gateway: 10.0.80.1
